# Generated by Django 5.2.6 on 2025-10-28 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comname', models.CharField(max_length=100)),
                ('comtext', models.TextField()),
                ('commented_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
